---
title: "Mitos y leyendas acerca de la visibilidad de las publicaciones periódicas. Un análisis estadístico del impacto de las publicaciones de la Universidad Nacional de La Matanza (UNLaM)"
author:
  - name: Melina Johanna Levy
    orcid: 0009-0008-4081-7150
    email: melinalevy95@gmail.com
    role:
      - conceptualization
      - investigation
      - methodology
      - writing
    affiliation: 
      - name: Universidad Nacional de La Matanza
        city: San Justo
        state: Buenos Aires
        country: AR
        url: https://ror.org/01bmj8t37
        ror: https://ror.org/01bmj8t37
  - name: Juan Pablo Piñeiro
    orcid: 0009-0000-2151-5749
    email: jpp@unlam.edu.ar
    role:
      - investigation
      - methodology
      - writing
    affiliation: 
      - name: Universidad Nacional de La Matanza
        city: San Justo
        state: Buenos Aires
        country: AR
        url: https://ror.org/01bmj8t37
        ror: https://ror.org/01bmj8t37
  - name: Yanina Soledad Amarilla
    orcid: 0000-0002-2011-2275
    email: yamarilla@unlam.edu.ar
    role:
      - investigation
      - writing
    affiliation: 
      - name: Universidad Nacional de La Matanza
        city: San Justo
        state: Buenos Aires
        country: AR
        url: https://ror.org/01bmj8t37
        ror: https://ror.org/01bmj8t37
date: 5/30/2025
abstract: |
  La literatura especializada en producción y transferencia del conocimiento ha indagado sobre el impacto de las publicaciones científicas a través de la visibilidad del conocimiento, a lo largo de las últimas décadas. Como resultado de tales indagaciones teóricas se han promovido supuestos, aún vigentes, acerca de la incidencia del idioma, la indización de las revistas en las cuales se publican las producciones, y el grado de reconocimiento formal e informal que ostentan los autores de las publicaciones; en detrimento de la incidencia que podría tener el hecho de que las publicaciones estén disponibles en Acceso Abierto.
  
  En ese marco, el objetivo de este capítulo es analizar la incidencia de distintos factores, en particular la disponibilidad en Acceso Abierto, en la visibilidad de las publicaciones producidas por docentes investigadores de la Universidad Nacional de La Matanza (UNLaM) durante el año 2022. La estrategia metodológica es mixta, ya que, combina un enfoque cualitativo, a partir del análisis documental, con el cuantitativo, a través del análisis estadístico. De esta forma, se ha seleccionado un año en el que, los registros históricos elevados por la UNLaM en la última Evaluación Institucional, que desarrolla la Comisión Nacional de Evaluación y Acreditación Universitaria (CONEAU)^[Esta agencia es un organismo descentralizado de nivel nacional, creado por la Ley 24.521/95, abarcando una diversidad de funciones: coordinar y realizar evaluaciones externas, acreditar carreras de grado y posgrado, evaluar la consistencia y viabilidad del proyecto institucional requerido para autorizar la creación de una nueva institución universitaria nacional, y, por último, elaborar los informes solicitados para la autorización y reconocimiento definitivo de universidades privadas.], señalan la recuperación plena de actividad científico-académica, posterior a la finalización de la Pandemia COVID-19. Adicionalmente, estas publicaciones aún no se encontraban influidas por el Fondo para Publicaciones y Traducciones de producciones científicas en SCOPUS — HCS 41/2024—, un fondo de financiamiento específicamente destinado a la promoción de artículos publicados en revistas aranceladas, implementado en la UNLaM a partir del año 2024.
  
  De esta forma, con esta investigación, se espera, por un lado, contribuir teóricamente con las discusiones propias del campo académico Ciencia, Tecnología y Sociedad; y, por otro lado, contribuir a la toma de decisiones y formaciones de políticas científicas universitarias, en particular, en el marco de la Secretaría de Ciencia y Tecnología de la Universidad Nacional de La Matanza.
keywords: 
  - publicaciones
  - visibilidad
  - impacto
  - acceso abierto
  - análisis estadístico
  - evaluación universitaria
license: "CC-BY"
doi: 10.62059/editorial.l001.c6
citation:
  type: chapter
  container-title: "Mitos y leyendas acerca de la visibilidad de las publicaciones periódicas. Un análisis estadístico del impacto de las publicaciones de la Universidad Nacional de La Matanza (UNLaM)"
  doi: 10.62059/editorial.l001.c6
lang: es
---

\chapterdoi{10.62059/editorial.l001.c6}
\chapterauthors{Melina Johanna Levy$^1$, Juan Pablo Piñeiro$^1$, Yanina Soledad Amarilla$^1$}
\chapteraffiliations{$^1$Universidad Nacional de La Matanza, San Justo, Buenos Aires, Argentina}

## Introducción {.unnumbered}

Durante las últimas décadas, los artículos científicos se han consolidado como producciones críticas para el ingreso y progreso en la carrera científica de los docentes investigadores tanto a nivel mundial [@gallardo2022] como, en particular, dentro del continente latinoamericano [@invernizzi2022]. Ello ha sido estimulado, principalmente, por los mecanismos de evaluación implementados sobre los investigadores, sus producciones y las instituciones a las que forman parte [@krauss2023]. A esta tendencia se la ha agregado la creciente publicación de dichas producciones en revistas diseñadas bajo el formato *Open Access.*

El formato *Open Access* implica que los autores no deben abonar ningún tipo de costo para poder acceder al contenido de una publicación. Si bien con anterioridad, coexistan dentro de este formato, revistas que le cobraban cargos al autor para gestionar parte del proceso editorial de revisión, gracias a la masividad alcanzada por la vía diamante, las revistas ha tendido a suprimir los cargos aplicados a los autores [@otero2022], haciendo posible una completa libre circulación del conocimiento. De esta forma, se han extendido modelos de gestión de las publicaciones científicas que promueven el aporte voluntario de los evaluadores, quienes no perciben por su contribución ninguna compensación económica [@canton2021].

Frente a ello, distintos investigadores han teorizado acerca de la incidencia del Acceso Abierto (AA) en la visibilidad de los artículos científicos — reflejado en la cantidad de citas obtenidas— aunque sin contrastarlo estadísticamente [@cordoba2011; @gonzalez2018; @diaz2023]. A su vez, otros factores— el idioma de la publicación, la cantidad de autores firmantes, y el nivel máximo de indización de la revista científica— han sido considerados, de forma individual, como determinantes de la visibilidad de las publicaciones científicas [@gonzalez2020].

En ese marco, el objetivo de este capítulo es analizar la incidencia de distintos factores, en particular la disponibilidad en AA, en la visibilidad de las publicaciones producidas por docentes investigadores de la UNLaM durante el año 2022. La estrategia metodológica es mixta, ya que, combina un enfoque cualitativo, a partir del análisis documental, con el cuantitativo, a través del análisis estadístico, mediante la utilización del programa RStudio. Para ello, se ha seleccionado un año en el que, los registros históricos elevados ante la última Evaluación Institucional de la Comisión Nacional de Evaluación y Acreditación Universitaria (CONEAU), [@pineiro2024a], señalan la recuperación plena de la actividad científico-académica, posterior a la finalización de la Pandemia COVID-19.

El presente capítulo se ha estructurado en cuatro grandes apartados. El primero de ellos describe la estrategia metodológica utilizada en este trabajo. El segundo aparado introduce el enfoque teórico del que se nutre este trabajo. El tercero caracteriza la producción de conocimiento en general, y en particular en el año 2022, en la UNLaM. El cuarto apartado analiza la incidencia, individual y agregada, de diez factores, sobre la cantidad de citas de los artículos publicados por docentes investigadores de la UNLaM en el año 2022. Finalmente, en el quinto apartado se sintetizan los principales hallazgos encontrados a lo largo del capítulo.

## Metodología

Esta investigación ha sido elaborada a partir de la combinación de estrategias cualitativas y cuantitativas. En relación con las primeras, se recopiló normativa y bibliografía relativa a los determinantes de la circulación del conocimiento, y sobre ella se realizó un análisis documental [@casasempere2020]. Con respecto a las segundas, a partir de un conjunto de variables —listadas en la @tbl-variables— se examinó la visibilidad de 160 artículos científicos publicados por docentes investigadores de la UNLaM durante el año 2022 en revistas científicas arbitradas e indizadas [@rivas2020].

```{=html}
<table id="tbl-variables">
  <caption>Variables incluidas en el análisis. Elaboración propia.</caption>
  <colgroup>
    <col width="30%"> <!-- Ancho para la columna "Aplicación" -->
    <col width="50%"> <!-- Ancho para la columna "Variables" -->
    <col width="20%"> <!-- Ancho para la columna "Tipo" -->
  </colgroup>
  <thead>
    <tr>
      <th>Aplicación</th>
      <th>Variables</th>
      <th>Tipo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="8">Sobre los artículos</td>
      <td>Cantidad de Citas</td>
      <td>Dependiente</td>
    </tr>
    <tr>
      <td>Campo disciplinar</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td>Cantidad de Autores</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td>Colaboración internacional en la coautoría</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td>Agenda temática</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td>Metodología</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td>Máximo título académico alcanzando por el primer autor</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td>Idioma</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td rowspan="3">Sobre la revista</td>
      <td>Indización</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td>Tipo de Acceso</td>
      <td>Independiente</td>
    </tr>
    <tr>
      <td>Frecuencia de publicación</td>
      <td>Independiente</td>
    </tr>
  </tbody>
</table>
```

A los efectos de estimar la visibilidad de los referidos artículos, se tomó en consideración la cantidad de citas obtenidas por cada uno de estos. El dato ha sido extraído de la plataforma Google Académico^[https://scholar.google.es/schhp?hl=es].

Por su parte, el campo disciplinar en el que se inscribe cada publicación, la cantidad de autores que la firman, la presencia de coautores pertenecientes a instituciones extranjeras, la correspondencia de la temática seleccionada con las agendas de interés nacional, la metodología, el máximo título académico alcanzado por el primer autor, y el idioma, han sido observados en estas. En el caso de las variables: tipo de acceso, máximo nivel de indización alcanzado y cantidad de números publicados por año, han sido extraídas de las respectivas revistas en las cuales se han publicado los artículos.

Para comenzar, se testeó la asociación entre cada variable independiente y la cantidad de citas obtenidas por cada artículo publicado, de forma individual. En segundo lugar, se realizó un análisis de regresión lineal múltiple [@inzunza2016], con aquellas variables cuya asociación resultó estadísticamente significativa y con elevada incidencia respecto de la cantidad de citas de los artículos, en un modelo aditivo.

De esta forma, se analizó la capacidad explicativa de un modelo integral de factores respecto de la visibilidad de las 160 observaciones registradas para el año 2022. La totalidad de las pruebas estadísticas se han realizado a través del programa de análisis estadístico RStudio^[https://posit.co/download/rstudio-desktop/].

## El Acceso Abierto y sus implicancias en la visibilidad de los artículos científicos

Desde su aparición, el AA ha sido considerado un movimiento orientado a la democratización del acceso al conocimiento científico [@suber2006]. Distintos autores han argumentado que, el AA permite otorgar mayor visibilidad a las investigaciones científicas [@cordoba2011; @gonzalez2018; @diaz2023], y ha incrementado las oportunidades de los científicos de colaborar entre sí, quebrantando las barreras interpuestas por su nacionalidad [@fernandez2018], así como, ha favorecido la circulación del conocimiento científico de forma universal [@delgado2015], y ha diluido las asimetrías entre países periféricos y centrales [@melero2014], entre otras cuestiones.

Desde esta perspectiva, que celebra la libertad de producción y circulación del conocimiento, es que una gran proporción de autores promueven la aplicación del AA, particularmente, en Latinoamérica. Sin embargo, la condición de libertad que se invoca presenta algunas particularidades que conviene indagar en mayor profundidad.

Para comenzar, el conocimiento científico regulado por el AA se considera doblemente libre, ya que, por un lado, es producido voluntariamente por los científicos -y en su versión plena no implica costos para su publicación^[El Acceso Abierto implica la libre circulación del conocimiento, a partir de la gratuidad del acceso al conocimiento por parte de los lectores. Sin embargo, también se consideran de AA aquellas publicaciones en las cuales los autores pagan un costo —Article Processing Charges (APC)— por publicar [@carballo2022]] [@zukerfeld2010a]. Por otro lado, este conocimiento circula de forma irrestricta, debido a que, ningún lector debe abonar un costo específico para poder acceder a este.

Ahora bien, lo primero que se aprecia en esta doble conceptualización de la libertad es que, la gratuidad de la publicación, y la no limitación de su circulación, no implican la desaparición de la propiedad por parte del autor de la obra. Es decir, el AA se enmarca en las regulaciones que delimitan los derechos de propiedad intelectual, más específicamente, los derechos de autor, en el sistema capitalista de producción [@zukerfeld2010b]. Por ello, se combina con un tipo específico de regulación legal conocida como Creative Commons (CC) [@lebron]. Esto incide tanto en la circulación como en la capacidad de apropiación de dicho conocimiento – fenómeno que ha sido abordado por la literatura especializada [@carballo2022].

Recientemente, también se ha problematizado la factibilidad económica del AA, en la medida en que, una de sus vías —el acceso diamante que promueve la publicación de contenidos plenamente gratuitos desde la perspectiva de los autores y de los consumidores— se ha consolidado, frente a otras, tales como la vía dorada [@canton2021]. A diferencia de la vía diamante, aquellas revistas que se han insertado en la vía dorada, han cobrado cargos a los autores para solventar la gestión editorial —en especial para el pago de una remuneración económica a los evaluadores involucrados—. Sin embargo, la proliferación de revistas inscriptas en la vía diamante ha dado pruebas de la capacidad de convocatoria de revisores que realizan sus evaluaciones sin exigir un pago por ello [@desouza2024].

Asimismo, en este formato – AA- se publican producciones de variada naturaleza. No obstante, el artículo científico resulta ser una pieza crítica dentro de la configuración de las carreras científicas [@moreles2015], superando, en términos de puntaje y valoración, a las obras conceptuales [@mendoza2006] y demás tipos de producciones científicas.

Dada la trascendencia del artículo científico en el ingreso y progreso de las carreras científicas, la atención se centra, en esta investigación, sobre los determinantes de su visibilidad. En ese marco, distintos factores han sido conjeturas supuestas como determinantes clave de la visibilidad de un artículo, junto al tipo de acceso, dentro de la literatura especializada. Entre ellos se destacan: el nivel de indización de la revista, en la cual se encuentran publicados [@gonzalez2020]; el idioma de la producción [@hernandez2019]; la cantidad de autores que firman dicha publicación [@liberatore2018]; la participación de coautores provenientes de diferentes países [@degranda2009]; el campo disciplinar al que pertenece [@kreimer2016]; y la relevancia internacional de las temáticas abordadas en el marco del artículo [@invernizzi2022].

De esta manera, las hipótesis de los referidos autores se basan, en su mayoría, en supuestos de orden teórico conceptual, que no han sido contrastados estadísticamente de forma integral. A continuación, se presentan las características estructurales de la investigación en la UNLaM, caso de estudio seleccionado para examinar los factores determinantes de la visibilidad de los artículos científicos durante el año 2022.

## La producción y transferencia del conocimiento científico en la UNLaM

La UNLaM es una institución argentina, fundada en el año 1989, en lo que se ha dado en llamar la segunda oleada de creación de Universidades públicas [@pineiro2024a]. De esta forma, es posible identificar en su Estatuto la vocación de incidir en la configuración territorial -particularmente afectada por la vulnerabilidad [@desena2024]- tanto a través de la formación de profesionales, como de la producción de conocimiento innovador, y la extensión comunitaria [@pineiro2024b].

Ahora bien, a diferencia de buena parte del Sistema Universitario argentino, la Universidad se organiza a través de una estructura departamental [@levy2024]. En el año 2024 es posible hallar cinco Unidades Académicas -Departamentos- organizadas por Secretarías coordinadas a través de órganos rectores dependientes del Rectorado. En el caso de la función investigación, cada Unidad Académica posee una Secretaría de Investigación, y su órgano rector -de normalización organizativa [@cao2023; @levy2023]- es la Secretaría de Ciencia y Tecnología (SCyT) central, como se aprecia en la @fig-estructura.

![Estructura de la función investigación en la UNLaM. Fuente: [@levy2024].](img/unlam.png){#fig-estructura}

De esta forma, el estatuto universitario de la UNLaM establece que el conocimiento producido debe orientarse por la multidisciplinariedad y la búsqueda de dar respuesta a las principales demandas vigentes en el territorio en el cual se asienta. En esa línea, la SCyT ha impulsado una serie de políticas tendientes a estimular la articulación con el entramado socio-productivo local, como es el caso del Programa Transferir UNLaM^[https://cyt.unlam.edu.ar/index.php?seccion=17&idArticulo=755]. De igual modo, promueve la difusión de los resultados de investigación alcanzados en el marco de los proyectos institucionales, a través de presentaciones en Congresos, publicaciones de libros, y, particularmente, artículos científicos.

Dada la trascendencia que ha adquirido la circulación del conocimiento -tanto a nivel individual como institucional-, desde la SCyT se ha reglamentado una política de AA-Resolución 97/2013-, a partir de la cual se derivó la creación del Repositorio Institucional UNLaM. Dentro del Repositorio se alojan las tesis de posgrados finalizados en la Universidad, publicaciones científicas de sus docentes investigadores, las Revistas de la UNLaM^[Las revistas científicas de la UNLaM son las siguientes: ANTIGUA MATANZA, REDDI, RINERS, RIHUMSO, RINCE Y REDSAL. Disponibles en: https://revistas.unlam.edu.ar/] y los informes finales de los proyectos de investigación.

De esta forma, se destaca el impulso institucional hacia la libre circulación del conocimiento [@zukerfeld2010a] junto a la articulación con el territorio. Dicho esto, a continuación, se analizan los principales determinantes de las publicaciones UNLaM, tomando como base la visibilidad obtenida por los artículos científicos publicados, por sus investigadores, en el año 2022.

## La productividad de las publicaciones UNLaM y sus principales determinantes

Como se anticipó en el apartado metodológico, durante el año 2022 se registraron un total de 160 artículos científicos publicados por docentes investigadores UNLaM en revistas arbitradas e indizadas. Para comenzar con el análisis, cabe destacar que se detectaron cuatro variables determinantes del impacto y la visibilidad de una publicación, las mismas se presentan y analizan de mayor a menor incidencia.

En este aspecto, en primer lugar, pudimos observar que, el 18,75% están publicados en idioma inglés, de ello se destaca que algunos de sus autores se encuentran insertos en redes internacionales, mientras que, otros aún no. De esta forma, se podría inferir que los investigadores UNLaM asocian la publicación de artículos científicos en idioma inglés con la posibilidad de obtener mayor cantidad de citas a nivel global^[Para poder indagar en mayor profundidad acerca de esta cuestión, se debería ampliar el universo de publicaciones estadísticamente consideradas, a futuro.], independientemente de participar en redes internacionales.

Continuando con este razonamiento, testeamos la incidencia del idioma inglés en la visibilidad de las publicaciones UNLaM. Cabe aclarar que, durante el año elegido, las publicaciones en idioma extranjero han sido escritas exclusivamente en este idioma, razón por la cual el análisis se basa únicamente en esta lengua. Al respecto, pudimos advertir que, el idioma inglés se constituye como un determinante clave del impacto científico de una publicación. En consonancia, como se aprecia en la @tbl-regresion-idioma, cuando el artículo está publicado en inglés, este tiene en promedio 15,85 citas^[El idioma inglés, individualmente considerado, permite explicar el 10% de la variación de la cantidad de citas de las referidas producciones UNLaM.].

::: {#tbl-regresion-idioma}

| Statistical models |        |
|--------------------|--------|
|                    | **Modelo 3** |
| Constante          | 1.53   |
|                    | (2.66) |
| Idioma inglés      | 15.85*** |
|                    | (4.65) |
| R²                 | 0.10   |
| Adj. R²            | 0.09   |
| Núm. obs.          | 104    |
| \*\*\*p < 0.001; \*\*p < 0.01; \*p < 0.05 |        |

Regresión lineal simple sobre el idioma de la publicación. Elaboración propia con base en el relevamiento realizado.

:::

De este modo, el presente análisis nos da pie para interpretar que, dada la incidencia manifiesta del idioma inglés, la participación en redes internacionales de investigación permitiría obtener mayor impacto a la hora de publicar un artículo. Por este motivo, incorporamos en el análisis, a la colaboración internacional, como una variable independiente, a considerar.

En este sentido, destacamos que, el 32,5% de los artículos cuenta con un solo autor, mientras que, el 20,62% presenta algún coautor internacional. De esta forma, en segundo lugar, la colaboración internacional se reveló como una variable clave de la visibilidad de las publicaciones. Por ello, al realizar el análisis estadístico pudimos observar la gran incidencia que la participación de coautores internacionales tiene en la cantidad de citas obtenidas por un artículo científico, dado que, un artículo científico con colaboración de autores de otros países obtiene, en promedio, 10,49 citas^[Adicionalmente, la presencia de coautorías internacionales, individualmente considerada, permite explicar el 14% de la variación de la cantidad de citas de las referidas producciones UNLaM.], como se aprecia en la @tbl-colaboracion-internacional.

::: {#tbl-colaboracion-internacional}

| Statistical models |        |
|--------------------|--------|
|                    | **Modelo 4** |
| Constante          | 1.73   |
|                    | (0.91) |
| Colaboración Internacional | 10.49\*\*\* |
|                    | (2.04) |
| R²                 | 0.14   |
| Adj. R²            | 0.14   |
| Núm. obs.          | 159    |
| \*\*\*p < 0.001; \*\*p < 0.01; \*p < 0.05 |        |

Regresión lineal simple sobre la participación de autores internacionales. Elaboración propia con base en el relevamiento realizado.

:::

Asimismo, un elemento que debe ser considerado, en aquellos artículos científicos que participan coautores internacionales y ostentan la mayor visibilidad, es que los primeros autores no suelen ser argentinos. En este sentido, podemos ponderar la relevancia que la inserción en redes de investigación internacionales tiene para los autores nacionales [@invernizzi2022]. No obstante, se pudo advertir que, buena parte de los artículos publicados, por autores UNLaM, en idioma inglés, se realizan junto con autores que no han tenido vinculación con academias y/o equipos de investigación internacionales, pero que, a pesar de ello, consideran que, publicar en idioma inglés reportaría mayor visibilidad. Este hecho nos permite revisar la histórica tradición científica de publicar artículos priorizando el idioma de lectura esperado en su público lector [@pineiro2024a], que implicaba que los autores hispanoamericanos tuvieran como propósito la publicación de artículos en idioma español ante la ausencia de participación en redes internacionales.

De esta forma, y ya en tercer lugar, que la revista se encuentre indizada en SCOPUS representa otro determinante clave del impacto y la visibilidad de una publicación. Así, un artículo UNLaM publicado en una revista indizada en SCOPUS obtiene, en promedio, 9,43 citas, como se observa en la @tbl-indizacion-scopus^[En este modelo de regresión lineal simple, la indización de una revista en la referida Base de Datos permite explicar el 14% de la variación de la cantidad de citas de las referidas producciones UNLaM.]. Este resultado preliminar refuerza la hipótesis de que, el grado de indización de una revista científica tiene efectos sobre su impacto y visibilidad en el universo académico. A su vez, esto podría deberse a la legitimidad que se atribuye a sus sistemas de evaluación [@invernizzi2022].

::: {#tbl-indizacion-scopus}

| Statistical models |        |
|--------------------|--------|
|                    | **Modelo 5** |
| Constante          | 1.47   |
|                    | (0.95) |
| Indizado en SCOPUS | 9.43\*\*\* |
|                    | (1.89) |
| R²                 | 0.14   |
| Adj. R²            | 0.13   |
| Núm. obs.          | 159    |
| \*\*\*p < 0.001; \*\*p < 0.01; \*p < 0.05 |        |

Regresión lineal simple sobre la indización de las publicaciones UNLaM en SCOPUS. Elaboración propia con base en el relevamiento realizado.

:::

De la misma manera, en cuarto lugar, de la @tbl-metodologia-cuantitativa se desprende que, a la colaboración internacional, el idioma inglés y la indización de la revista en SCOPUS, se le agrega una variable más como determinante clave. Se trata de un factor que especialistas como [@calvo2019] han abordado en relación con su escasa expresión dentro de las academias argentinas. Nos referimos a la utilización de una estrategia metodológica cuantitativa de investigación.

Del total de artículos analizados, el 26,25% presentan estrategias metodológicas cuantitativas. De acuerdo con la @tbl-metodologia-cuantitativa, cuando la metodología del artículo es cuantitativa, este tiene en promedio 9,02 citas^[La variación en el tipo de metodología empleada por los autores, individualmente considerada, permite explicar el 13% de la variación de la cantidad de citas de las referidas producciones UNLaM.].

::: {#tbl-metodologia-cuantitativa}

| Statistical models |        |
|--------------------|--------|
|                    | **Modelo 6** |
| Constante          | 1.52   |
|                    | (0.96) |
| Metodología Cuantitativa | 9.02\*\*\* |
|                    | (1.89) |
| R²                 | 0.13   |
| Adj. R²            | 0.12   |
| Núm. obs.          | 159    |
| \*\*\*p < 0.001; \*\*p < 0.01; \*p < 0.05 |        |

Regresión lineal simple sobre el tipo de metodología empleada. Elaboración propia con base en el relevamiento realizado.

:::

En este punto, se destaca que los especialistas parten del supuesto de que aquellas investigaciones que incorporan estrategias cuantitativas para alcanzar los objetivos propuestos suelen estar conectadas con equipos y redes de investigación internacionales [@calvo2019]. Nuevamente, la hipótesis de la participación en redes de colaboración internacional, que publican en idioma inglés, en revistas indizadas en SCOPUS y emplean este tipo de metodologías, parece consistente.

Ahora bien, más adelante, se incorporaron al análisis otras dos variables -principalmente para controlar el efecto de las anteriores-, y que poseen menor incidencia en el impacto y la visibilidad de una publicación. Estas han sido la cantidad total de autores que firman una publicación y la periodicidad de la revista en la cual se encuentra incluido el artículo científico. Se partía del supuesto de que, una mayor cantidad de coautores podría traccionar más citas por el aporte individual de visibilidad que podría realizar cada uno de ellos. Adicionalmente, una revista que se publica con mayor frecuencia podría suscitar mayor atención en la respectiva comunidad científica, por la periodicidad del contacto con los lectores y las exigencias propias de algunos índices que no evalúan a revistas con menos de dos entregas al año.

Al respecto, pudimos observar que, si bien la cantidad de autores incide en la visibilidad de una publicación, lo hace de forma moderada. De hecho, como se visualiza en la @tbl-cantidad-autores, por cada autor incorporado a un artículo, este no llega a incrementar ni 2 citas completas, en promedio^[La variación en la cantidad de autores, individualmente considerada, permite explicar el 28% de la variación de la cantidad de citas de las referidas producciones UNLaM.].

::: {#tbl-cantidad-autores}

| Statistical models |        |
|--------------------|--------|
|                    | **Modelo 7** |
| Constante          | -2.02  |
|                    | (1.05) |
| Cantidad de Autores | 1.67\*\*\* |
|                    | (0.21) |
| R²                 | 0.29   |
| Adj. R²            | 0.28   |
| Núm. obs.          | 159    |
| \*\*\*p < 0.001; \*\*p < 0.01; \*p < 0.05 |        |

Regresión lineal simple con la cantidad de autores. Elaboración propia con base en el relevamiento realizado.

:::

De forma análoga, la periodicidad de una revista no parece tener gran impacto en la visibilidad de sus artículos. Estadísticamente, la @tbl-periodicidad-revista revela que, por cada número adicional publicado por la revista, esta obtiene en promedio 1 cita más^[La variación en la frecuencia de la publicación de una revista, individualmente considerada, permite explicar el 15% de la variación de la cantidad de citas de las referidas producciones UNLaM.].

::: {#tbl-periodicidad-revista}

| Statistical models |        |
|--------------------|--------|
|                    | **Modelo 8** |
| Constante          | -0.21  |
|                    | (1.11) |
| Frecuencia de publicación de la Revista | 1.14\*\*\* |
|                    | (0.21) |
| R²                 | 0.15   |
| Adj. R²            | 0.15   |
| Núm. obs.          | 159    |
| \*\*\*p < 0.001; \*\*p < 0.01; \*p < 0.05 |        |

Regresión lineal simple sobre frecuencia de publicación de la revista. Elaboración propia con base en el relevamiento realizado.

:::

Al mismo tiempo, identificamos un conjunto de variables que no parecen haber incidido en la cantidad de citas obtenidas por los artículos UNLaM considerados. Del total de artículos, el 88,12% se encuentra publicado en revistas de AA. En este aspecto, el primer dato destacado es que, probablemente debido a la sobrerrepresentación del AA en la población analizada, la asociación de esta variable con la cantidad de citas por artículo no ha resultado estadísticamente significativa. Sin embargo, el amplio porcentaje de artículos publicados bajo este formato nos permite inferir que, mayoritariamente, los investigadores UNLaM apuestan por la libre circulación del conocimiento.

En este sentido, resulta menester recalcar que, la elección por el formato en AA se enmarca en un contexto nacional de búsqueda de promoción de la libre circulación del conocimiento, estimulado por la Ley 26.899/13^[Disponible en: https://servicios.infoleg.gob.ar/infolegInternet/anexos/220000-224999/223459/norma.htm]. En esta misma línea, la UNLaM aprobó una Resolución en adhesión a esta Ley. No obstante, más allá de estas normativas, la significativa tendencia de publicar artículos científicos en AA, por parte de los investigadores UNLaM, permite vislumbrar una expectativa de alcanzar mayor visibilidad, a través de esta.

A ello se añade que, en la población seleccionada hay científicos que pertenecen tanto a la UNLaM como a otras instituciones, simultáneamente, tales como el CONICET, que siguiendo a [@beigel2017], promueven la búsqueda de elevados factores de impacto y citación a través de las evaluaciones realizadas a sus científicos -tanto becarios como de carrera. En esa línea, se visualiza una elevada expectativa de visibilidad de las publicaciones asociada con el AA.

Otra de las variables que no fue significativa en relación con la cantidad de citas obtenidas en promedio, es el máximo título académico alcanzado por el primer autor de la publicación. En este sentido, pudimos observar que del 65% de los artículos publicados, el primer autor tiene formación doctoral. De este modo, se advirtió que la asociación entre la visibilidad de las publicaciones y la máxima titulación académica alcanzada por el primer autor no resultó relevante. Ello puede deberse a que, la gran mayoría de los artículos analizados han sido publicados por primeros autores con doctorados finalizados. Es decir, al igual que con la variable AA, se evidencia una sobrerrepresentación de primeros autores con formación doctoral en la población analizada.

Adicionalmente, este mismo efecto de sobrerrepresentación se pudo corroborar en relación con las últimas dos variables incorporadas en este análisis. Por un lado, pudimos observar que, el 61,25% de las publicaciones pertenece a la disciplina Ciencias Sociales. Por otro lado, y en esa línea, el 63,75% de los artículos aborda temas de relevancia nacional^[Sobre esta cuestión, cabe aclarar que, se consideró la relevancia nacional en función del territorio analizado.]. De esta forma, tanto la disciplina como la relevancia de la temática abordada no resultaron significativas para explicar la visibilidad y el impacto de las publicaciones.

A continuación, se sintetizan las variables analizadas y su grado de incidencia sobre la cuestión estudiada.

::: {#tbl-grado-incidencia}

| Factores | Grado de incidencia |
|----------|:-------------------:|
| Idioma inglés | Determinante |
| Colaboración internacional | Determinante |
| Indización en Scopus | Determinante |
| Metodología cuantitativa | Determinante |
| Cantidad de Autores | Moderada |
| Frecuencia de la publicación de la revista | Moderada |
| Acceso Abierto | No significativa |
| Título doctoral alcanzado por el primer autor de la publicación | No significativa |
| Artículo inscripto en el área de las Ciencias Sociales | No significativa |
| Relevancia nacional de los resultados de la publicación | No significativa |

Grado de incidencia en la visibilidad e impacto de las publicaciones UNLaM de los factores analizados. Elaboración propia con base en el relevamiento realizado.

:::

Hasta el momento, se ha presentado el análisis individual de la incidencia de diez variables - @tbl-grado-incidencia- en la cantidad promedio de citas obtenidas por los artículos publicados por investigadores UNLaM durante el año 2022. De esta primera etapa podemos inferir que, individualmente consideradas, el idioma inglés, la colaboración internacional, la indización de la revista en SCOPUS y la metodología cuantitativa son determinantes de los artículos examinados.

Posteriormente, elaboramos un modelo aditivo, conformado por las variables determinantes analizadas individualmente para observar el comportamiento de cada una de estas cuando se controla el efecto de las restantes. Esto nos permite comprender, en mayor profundidad, en qué medida cada factor incide sobre la cantidad de citas obtenidas por una publicación científica, dado que, de no controlar el efecto de otras variables relevantes, podríamos llegar a la errónea conclusión de que alguna de estas tiene más peso que las demás.

::: {#tbl-modelo-aditivo}

| Statistical models |        |
|--------------------|--------|
|                    | **Modelo 10** |
| Constante          | -0.08  |
|                    | (0.98) |
| Indización en SCOPUS | 4.55\* |
|                    | (2.13) |
| Colaboración Internacional | 4.46 |
|                    | (2.50) |
| Metodología Cuantitativa | 4.10 |
|                    | (2.09) |
| Idioma inglés      | 3.10   |
|                    | (2.37) |
| R²                 | 0.23   |
| Adj. R²            | 0.21   |
| Núm. obs.          | 159    |
| \*\*\*p < 0.001; \*\*p < 0.01; \*p < 0.05 |        |

Modelo aditivo de factores determinantes de la visibilidad de las publicaciones UNLaM. Elaboración propia con base en el relevamiento realizado.

:::

A partir de la @tbl-modelo-aditivo podemos realizar una serie de inferencias clave. Para comenzar, podemos aseverar que, un artículo que no se encuentre publicado en idioma inglés, ni en una revista indizada en SCOPUS, que no posea colaboración internacional en su autoría, y cuya estrategia metodológica sea cualitativa, obtendría en promedio ninguna cita. En segundo lugar, se advierte que, al comparar la incidencia individual de cada factor en la cantidad de citas obtenidas en promedio, por las publicaciones UNLaM consideradas, en el modelo aditivo los valores tienden a moderarse.

De ello se desprende que, al controlar el efecto de la indización, la colaboración internacional, y la metodología utilizada, un artículo científico publicado en inglés obtiene en promedio 3 citas. A su vez, si mantenemos controlado el efecto del idioma, la indización y la colaboración internacional, un artículo cuya estrategia metodológica es cuantitativa tiene un promedio de 4 citas. En esa línea, controlando el efecto del idioma, la indización y la metodología, una publicación científica con colaboración internacional recibe, en promedio, 4,4 citas. Finalmente, controlando el efecto de la colaboración internacional, el idioma y la metodología, un artículo publicado en una revista indizada en SCOPUS obtiene en promedio 4,5 citas.

De esta forma, se aprecia que, tanto consideradas de forma individual, como integrada en un modelo de regresión lineal múltiple aditivo, que nos permite controlar el efecto de las restantes variables incluidas, cada factor tiene incidencia en la cantidad media de citas obtenidas por un artículo científico. Sin embargo, este efecto se modera en el modelo aditivo, demostrando que, si bien han afectado la visibilidad de las publicaciones UNLaM durante el año 2022, la incidencia ha sido menor a la esperada a partir de los resultados arrojados por el análisis individual. Si en el modelo individual la incidencia rondaba entre las 9 y las 15 citas promedio, en el modelo aditivo no supera las 5 citas en ningún caso.

## Conclusiones

El objetivo de este capítulo fue analizar la incidencia de distintos factores, en particular la disponibilidad en AA, en la visibilidad de las publicaciones producidas por docentes investigadores UNLaM, durante el año 2022. La estrategia metodológica fue mixta, ya que, se combinó un enfoque cualitativo, a partir del análisis documental, con el cuantitativo, a través del análisis estadístico, a través del programa de análisis estadístico RStudio.

Para ello, se han considerado un total de diez variables, dentro de las cuales, la dependiente fue la cantidad de citas obtenidas por cada artículo científico, y las independientes fueron: campo disciplinar, cantidad de autores, colaboración internacional, agenda temática, metodología, máximo título académico alcanzado por el primer autor, idioma, indización, tipo de acceso, y, por último, frecuencia de publicación. De esta forma, se examinó la visibilidad de 160 artículos científicos publicados por docentes investigadores UNLaM durante el año 2022 en revistas científicas.

El enfoque teórico de esta investigación retomó la importancia del AA para incrementar la visibilidad de las publicaciones científicas. Adicionalmente, se consideró la incidencia de otros factores, como, por ejemplo, la indización de las revistas, el idioma, así como el perfil de los autores involucrados en una publicación, que han sido abordados teóricamente, por parte de la literatura especializada, pero no empíricamente.

Como resultado, pudimos observar que, hay una tendencia general, en los investigadores UNLaM, ha seleccionar publicaciones inscriptas en la tradición del AA. Ello ha permeado a las distintas disciplinas a las que pertenecen los autores de los artículos seleccionados, exhibiendo una apuesta masiva por la circulación libre del conocimiento.

Sin embargo, se advirtió que, en primer lugar, probablemente debido a la sobrerrepresentación del AA en la población de artículos, la asociación de esta variable con la cantidad de citas por artículo no resultó estadísticamente relevante, al igual que la máxima titulación académica alcanzada por el primer autor. De las restantes variables, en cuyo caso pudimos descartar la hipótesis nula, es decir, la inexistencia de asociación con la variación en la cantidad de citas obtenidas por artículo científico, se seleccionaron las cuatro variables con mayor capacidad de explicación de la variación de la visibilidad de los artículos, de acuerdo con los modelos de regresión lineal simple realizados.

Del mismo modo, pudimos arribar a las siguientes conclusiones: por cada número adicional publicado por la revista, esta obtiene, en promedio 1,14 citas más; por cada autor incorporado a un artículo, cada artículo aumenta en promedio 1,67 citas; cuando la metodología del artículo es cuantitativa, este tiene en promedio 9,02 citas; un artículo publicado en una revista indizada en la Base de Datos SCOPUS obtiene, en promedio, 9,43 citas; ante la presencia de la colaboración internacional, un artículo obtiene, en promedio, 10,49 citas; cuando el artículo científico está publicado en inglés, este tiene en promedio 15,85 citas. En este sentido, se advierte que, las últimas cuatro variables se constituyen como factores críticos que inciden en la visibilidad de las producciones científicas de la UNLaM.

Posteriormente, integramos las cuatro variables con mayor capacidad explicativa de la variación en la cantidad promedio de citas recibidas por un artículo científico en un mismo modelo aditivo, para observar cómo se comportaban al controlar el efecto de las restantes. De esta forma, pudimos apreciar que, en el modelo múltiple, las cuatro variables resultaron estadísticamente significativas. No obstante, mientras que en el modelo individual la incidencia rondaba entre las 9 y las 15 citas promedio, en el modelo aditivo no supera las 5 citas en ningún caso. De esta forma, se visualizó que la incidencia de estas variables, de forma integral, es consistente, pero menor, a la esperada.

De esta investigación se desprende la necesidad de ampliar la base de datos observacionales, más allá del año 2022, para corroborar los resultados alcanzados en una serie de tiempo extendida. Adicionalmente, resultaría de interés poder contrastar estos resultados con otras instituciones del Sistema Nacional de Ciencia, Tecnología e Innovación de Argentina.