---
title: O papel da Rede Ibero-Americana de Editores Científicos de Educação (RIECE) no fortalecimento da comunicação científica em periódicos da área de Educação
author:
  - name: Lia Machado Fiuza Fialho
    orcid: 0000-0003-0393-9892
    email: lia_fialho@yahoo.com.br
    affiliation: 
      - name: Universidade Estadual do Ceará
        city: Fortaleza
        state: CE
        country: BR
        url: https://www.uece.br
        ror: https://ror.org/00sec1m50
  - name: Karla Angélica Nascimento
    orcid: 0000-0001-6103-2397
    email: karla.asn@gmail.com
    affiliation: 
      - name: Universidade Estadual do Ceará
        city: Fortaleza
        state: CE
        country: BR
        url: https://www.uece.br
        ror: https://ror.org/00sec1m50
  - name: Maria Aparecida Alves da Costa
    orcid: 0000-0001-5213-4869
    email: mariapedagoga99@gmail.com
    affiliation: 
      - name: Instituto Federal de Educação, Ciência e Tecnologia do Ceará
        city: Fortaleza
        state: CE
        country: BR
        url: https://www.ifce.edu.br
        ror: https://ror.org/02225fd27
date: 1/16/2025
abstract: |
  O capítulo trata acerca da fundação da Rede Ibero-americana de Editores Científicos de Educação (RIECE) e do seu desenvolvimento de atividades no âmbito da articulação internacional para o fortalecimento da comunicação científica nos países latino-americanos, caribenhos e africanos. O objetivo é apresentar à comunidade internacional como se deu a articulação entre os editores dos países integrantes da rede para a criação da RIECE destacando as experiências colaborativas exitosas para majorar a internacionalização, indexação e aderência à ciência aberta nos periódicos envolvidos. Metodologicamente, adota-se uma pesquisa qualitativa, do tipo documental, que utiliza como fonte o projeto da RIECE, o documento diagnóstico, as atas das reuniões e os relatórios de atividades. Os resultados mostram que a RIECE se iniciou com a articulação de 11 países - Brasil, Colômbia, México, Venezuela, Costa Rica, Angola, Uruguai, Espanha, Portugal, Paraguai e Equador – e o apoio de importantes entidades que apoiam a editoria de revistas científica, a exemplo do Redalyc, do Latindex, do EDUC@, da AURA e da ABEC Brasil. Essa iniciativa foi aprovada pelo Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq), entidade ligada ao Ministério da Ciência, Tecnologia e Inovações para incentivo à pesquisa no Brasil, que concedeu apoio financeiro mediante verba de custeio e 15 bolsas internacionais, o que estimulou os participantes do projeto. O trabalho inicial da RIECE amparou-se na pesquisa-ação, partindo de um minucioso diagnóstico das revistas científicas, para, em seguida, mediante questionário, grupo focal e relato textual elaborar um plano de desenvolvimento colaborativo dos periódicos. Conclui-se que a RIECE vem colaborando para qualificar científica e tecnologicamente os periódicos de Educação a partir da articulação dos conhecimentos editoriais da equipe compartilhados voluntariamente, consoante a ciência aberta, entre os seus integrantes. Sua principal meta é ampliar o número de países da rede e aumentar os editores de educação comprometidos com a proposta.
keywords: 
  - editoria científica
  - revista científica
  - ciência aberta
  - internacionalização
license: "CC-BY"
doi: "10.62059/editorial.l001.c10"
citation:
  type: chapter
  container-title: "O papel da Rede Ibero-Americana de Editores Científicos de Educação (RIECE) no fortalecimento da comunicação científica em periódicos da área de Educação"
  doi: "10.62059/editorial.l001.c10"
lang: pt
reference-section-title: Referências

---

## Introdução

O capítulo trata acerca da fundação da Rede Ibero-Americana de Editores Científicos de Educação (RIECE) e do desenvolvimento de atividades no âmbito da articulação internacional proporcionada pela RIECE para o fortalecimento da comunicação científica nos países latino-americanos, caribenhos e africanos.

A principal área coberta pela RIECE é a Educação, pois a articulação centra-se em periódicos desse campo do conhecimento, com o mote de qualificação contínua dos editores científicos considerando as especificidades da área e a necessária articulação do sul global para o fortalecimento da ciência nos países em desenvolvimento @Fialho2024. Ademais, a troca de saberes e conhecimentos editoriais entre os editores tem sido fundamental para a formação profissional dos editores científicos, já que, em quase a totalidade dos países latino-americanos, caribenhos e africanos, não há uma habilitação específica em nível de graduação ou pós-graduação para a formação de editores científicos, inclusive, constata-se ausência de regulamentação para o exercício dessa atividade laboral em diversos países (@Morais2022).

Majoritariamente, os editores de revistas científicas na Iberoamérica são professores doutores, vinculados a instituições de ensino superior públicas ou privadas, que assumem essa função como parte de suas atividades laborais de pesquisa e gestão (Fontes, 2021). Destaca-se, inclusive, que em diversos casos é realizado de maneira voluntária, sem atribuição de carga horária ou benefício financeiro extra, em condições precarizadas, pela ausência de uma política institucional adequada de apoio e financiamento às necessidades da publicação científica (Werlang, Carlim & Rode, 2021).

Considerando o exposto, o objetivo deste texto é apresentar à comunidade internacional como se deu a articulação entre os editores de diversos países para a criação da RIECE, destacando as experiências colaborativas exitosas para majorar a internacionalização, indexação e aderência à ciência aberta nos periódicos envolvidos, bem como a maneira pela qual outros editores da área de Educação podem se juntar à Rede, somando esforços para fortalecer as revistas científicas, no seu papel fundamental de divulgar o conhecimento produzido por meio de pesquisas qualificadas.

O Brasil, neste caso, partiu como idealizador do projeto em rede e, inicialmente, coordenador central na articulação dos editores da área de Educação, com o apoio financeiro do Conselho Nacional de Desenvolvimento Científico e Tecnológico (CNPq), mediante aprovação de projeto denominado “Qualificação de periódicos científicos de Educação: articular para internacionalizar”, submetido sob a coordenação da pesquisadora brasileira Lia Machado Fiuza Fialho, na chamada do edital publicizado pelo Ministério da Ciência, Tecnologia e Inovações (MCTI) e CNPq, de número 14/2023. Outro apoio institucional importante foi o da Fundação Cearense de Apoio ao Desenvolvimento Científico e Tecnológico (Funcap), que também aprovou financiamento público para o projeto de criação da RIECE mediante chamamento via edital público de número 06/2023. De tal modo, a iniciativa já começou com a aprovação e o suporte financeiro de duas conceituadas instituições, respectivamente em nível federal e estadual. 

Consoante o edital MCTI/CNPq número 14/2023 e Funcap número 06/2023, o projeto buscou atender ao objetivo de “incentivar a participação de pesquisadores brasileiros em projetos de cooperação com grupos e/ou redes de pesquisa de países latino-americanos, caribenhos e africanos”; bem como o objetivo de “encorajar a participação em projetos internacionais de pesquisadores brasileiros vinculados a instituições sediadas nas regiões Norte, Nordeste e Centro-Oeste”. Dessa maneira, inicialmente, para a constituição da Rede, foram priorizados editores de países latino-americanos e das regiões brasileiras supramencionadas que apresentam maior dificuldade de desenvolvimento científico, todavia sem se olvidar de incluir países europeus com periódicos mais consolidados que se sensibilizaram para ajudar na internacionalização dos demais. Acrescenta-se ainda que, dentre os países mais desenvolvidos, priorizaram-se os que falam os mesmos idiomas – espanhol e português – dos países latinos, com o objetivo de evitar barreiras linguísticas, já que muitos editores não dominavam outros idiomas, a exemplo do francês e do inglês.

Justamente por reconhecer a importância da RIECE para a articulação no campo editorial ibero-americano e, em especial do sul global, considerou-se relevante divulgar essa Rede para a comunidade internacional, já que a propagação dessa iniciativa não apenas dar a ver o trabalho previamente executado, mas possibilita a sua divulgação e o seu fortalecimento mediante a união de outros editores da área de Educação, o que permite à RIECE crescimento em número de adeptos e fortalecimento para continuar atuando no fomento ao intercâmbio de saberes e conhecimentos e à consolidação das revistas científicas.

## Metodologia


See @knuth84 for additional discussion of literate programming.
